# Generated by Django 3.2.7 on 2022-03-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='problem',
            new_name='post',
        ),
    ]
